name: Task 1 Docker CI

on: 
  push: 
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd task-1-docker-ci
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd task-1-docker-ci
          pytest

      - name: Build Docker image
        run: |  
          cd task-1-docker-ci
          docker build -t helloapp .