name: Task 2 Terraform Lint

on:
  push:
    branches:
      - main

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform fmt check
        run: |
          cd task-2-terraform-lint
          terraform fmt -check