name: Task 2 Terraform Lint

on:
  push:
    branches:
      - main

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: |
          cd task-2-terraform-lint
          terraform fmt -check

      - name: Terraform init
        run: |
          cd task-2-terraform-lint
          terraform init -backend=false

      - name: Terraform validate
        run: |
          cd task-2-terraform-lint
          terraform validate